name: Deploy
on:
    push:
        branches:
            - develop
        paths:
            - 'force-app/main/default/**/*'

env:
    NODE_VERSION: 20.2.0
    TARGET_ORG_AUTH_URL: ${{ secrets.TARGET_ORG_AUTH_URL }}
    TARGET_ORG_LOGIN_USER: ${{ secrets.TARGET_ORG_LOGIN_USER }}
    SHA_BEFORE: ${{ github.event.before }}

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  fetch-depth: 2
            - name: Install Salesforce CLI
              run: |
                  npm install --global sfdx-cli@latest
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ env.NODE_VERSION }}
            - name: Authorize org
              run: |
                  rm -rf ~/.sf
                  rm -rf ~/.sfdx
                  echo "$TARGET_ORG_AUTH_URL" > auth.json
                  sfdx auth:sfdxurl:store -f auth.json -s
                  rm auth.json
            - name: Deploy
              run: |
                  rm -rf ~/.sf
                  rm -rf ~/.sfdx
                  export USER_EMAIL="${TARGET_ORG_LOGIN_USER}"
                  git config diff.renamelimit 10000
                  ulimit -s 131072
                  bash ./scripts/deploy/deployChanges.sh "origin/develop" "$SHA_BEFORE" DEPLOY "$GITHUB_WORKSPACE/force-app"
