name: Validate
on:
    pull_request:
        branches:
            - develop
        paths:
            - 'force-app/main/default/**/*'

env:
    NODE_VERSION: 20.2.0
    TARGET_ORG_AUTH_URL: ${{ secrets.TARGET_ORG_AUTH_URL }}
    TARGET_ORG_LOGIN_USER: ${{ secrets.TARGET_ORG_LOGIN_USER }}

jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  fetch-depth: 2
            - name: Install Salesforce CLI
              run: |
                  npm install --global sfdx-cli@latest
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ env.NODE_VERSION }}
            - name: Authorize org
              run: |
                  printf $TARGET_ORG_AUTH_URL > auth.json
                  sfdx auth:sfdxurl:store -f auth.json -s
                  rm auth.json
            - name: Validate with test
              run: |
                  export USER_EMAIL="${TARGET_ORG_LOGIN_USER}"
                  git config diff.renamelimit 10000
                  ulimit -s 131072
                  git fetch origin $GITHUB_HEAD_REF
                  git fetch origin $GITHUB_BASE_REF
                  bash ./scripts/deploy/deployChanges.sh "origin/$GITHUB_HEAD_REF" "origin/$GITHUB_BASE_REF" VALIDATE_WITH_TEST "$GITHUB_WORKSPACE/force-app"
